services:
  database:
    container_name: database
    image: mariadb:10.6
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "4306:3306"

    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./app
    container_name: app
    user: "${UID}:${GID}"
    restart: always

    ports:
      - "8080:80"

    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SASS_FORCE_POLLING: "true"

    volumes:
      - ./app:/var/www/html
      - ./app/apache/default.conf:/etc/apache2/sites-available/000-default.conf

    depends_on:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always

    ports:
      - "8899:8080"

volumes:
  db_data:
